# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- script: dir
- bash: mvn install
  workingDirectory: ./lab-spring-boot
- bash: docker build -t testaks:latest .  # add options to this command to meet your needs
  workingDirectory: ./lab-spring-boot
- bash: docker login secondaks.azurecr.io -u secondaks  -p $(containerPwd)
  workingDirectory: ./lab-spring-boot
- bash: docker push testaks:latest
  workingDirectory: ./lab-spring-boot