apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: party-clippy
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
  - host: myspringboot-service.#(DNS_NAME)
    http:
      paths:
      - backend:
          serviceName: myspringboot-service
          servicePort: 80
        path: /
